# Yarn configuration for Aki UI
nodeLinker: node-modules

# Package manager specification
packageManager: yarn@4.9.2

# Install settings
enableGlobalCache: false
enableTelemetry: false

# Peer dependency handling for React 19 compatibility
peerDependencyRules:
  allowedVersions:
    react: ">=18.0.0"
    react-dom: ">=18.0.0"
