# Yarn Berry configuration
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.0.2.cjs

# Enable corepack for package manager management
packageManager: yarn@4.0.2

# Dependency resolution
preferInteractive: true
enableGlobalCache: true

# Plugin settings
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

# Workspace configuration  
workspaces:
  - "."
  - "website"
  - "mcp"

# Install settings
checksumBehavior: update
enableTelemetry: false

# Cache settings
enableMirror: false
enableNetwork: true

# Resolution strategy for peer dependencies
peerDependencyRules:
  allowedVersions:
    react: ">=18.0.0"
    react-dom: ">=18.0.0"
