name: Deploy Website to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-website:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install root dependencies
        run: npm ci

      - name: Install website dependencies
        run: cd website && npm install

      - name: Build Aki UI library
        run: npm run build:prod

      - name: Build website
        run: npm run website:build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_GA_ID: ${{ secrets.NEXT_PUBLIC_GA_ID }}
          NEXT_PUBLIC_SITE_URL: https://aki-ui.akitect.io

      - name: Copy LLMs files to website
        run: |
          cp public/llms.txt website/out/
          cp public/llms-full.txt website/out/

      - name: Add .nojekyll file
        run: touch website/out/.nojekyll

      - name: Add CNAME file for custom domain
        run: echo "aki-ui.akitect.io" > website/out/CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./website/out"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
