name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version_increment:
        description: "Version increment type"
        required: true
        default: "patch"
        type: "choice"
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup .npmrc file to publish to npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Configure git
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Increment version
        if: github.event_name == 'workflow_dispatch'
        id: version
        run: |
          VERSION_TYPE="${{ github.event.inputs.version_increment }}"
          NEW_VERSION=$(npm --no-git-tag-version version $VERSION_TYPE)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Incremented version to $NEW_VERSION"

      - name: Prepare package for publishing
        run: |
          # Backup original files
          cp README.md README.md.backup

          # Use NPM README for publishing
          cp NPM_README.md README.md

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Restore original README
        run: |
          mv README.md.backup README.md

      - name: Commit version bump and push
        if: github.event_name == 'workflow_dispatch'
        run: |
          git add package.json package-lock.json
          git commit -m "chore: bump version to ${{ steps.version.outputs.new_version }}"
          git tag "${{ steps.version.outputs.new_version }}"
          git push origin main
          git push origin "${{ steps.version.outputs.new_version }}"

      - name: Create GitHub Release
        if: github.event_name == 'workflow_dispatch'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.new_version }}
          release_name: Release ${{ steps.version.outputs.new_version }}
          body: |
            ## Changes
            - Version bump to ${{ steps.version.outputs.new_version }}
            - Published to npm: https://www.npmjs.com/package/@akitectio/aki-ui

            ## Installation
            ```bash
            npm install @akitectio/aki-ui@${{ steps.version.outputs.new_version }}
            ```
          draft: false
          prerelease: false
