name: Publish to npm

on:
  push:
    branches: [main]
    paths-ignore:
      - "package.json"
      - "package-lock.json"
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version_increment:
        description: "Version increment type"
        required: true
        default: "patch"
        type: "choice"
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Check commit message
        id: check_commit
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"chore: bump version"* ]]; then
            echo "Skip workflow for version bump commits"
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout
        if: steps.check_commit.outputs.skip != 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup .npmrc file to publish to npm
      - name: Setup Node.js
        if: steps.check_commit.outputs.skip != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Verify npm authentication
        if: steps.check_commit.outputs.skip != 'true'
        run: |
          echo "Checking npm authentication..."
          npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        if: steps.check_commit.outputs.skip != 'true'
        run: npm ci

      - name: Build package
        if: steps.check_commit.outputs.skip != 'true'
        run: npm run build

      - name: Configure git
        if: steps.check_commit.outputs.skip != 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Increment version
        if: steps.check_commit.outputs.skip != 'true'
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION_TYPE="${{ github.event.inputs.version_increment }}"
          else
            # Auto increment patch version for push events
            VERSION_TYPE="patch"
          fi
          NEW_VERSION=$(npm --no-git-tag-version version $VERSION_TYPE)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Incremented version to $NEW_VERSION"

      - name: Prepare package for publishing
        if: steps.check_commit.outputs.skip != 'true'
        run: |
          # Backup original files
          cp README.md README.md.backup

          # Use NPM README for publishing
          cp NPM_README.md README.md

      - name: Verify package before publishing
        if: steps.check_commit.outputs.skip != 'true'
        run: |
          echo "Package contents:"
          npm pack --dry-run
          echo "Current npm user:"
          npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        if: steps.check_commit.outputs.skip != 'true'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Restore original README
        if: steps.check_commit.outputs.skip != 'true'
        run: |
          mv README.md.backup README.md

      - name: Commit version bump and push
        if: steps.check_commit.outputs.skip != 'true'
        run: |
          git add package.json package-lock.json
          git commit -m "chore: bump version to ${{ steps.version.outputs.new_version }}"
          git tag "${{ steps.version.outputs.new_version }}"
          git push origin main
          git push origin "${{ steps.version.outputs.new_version }}"

      - name: Create GitHub Release
        if: steps.check_commit.outputs.skip != 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.new_version }}
          release_name: Release ${{ steps.version.outputs.new_version }}
          body: |
            ## Changes
            - Version bump to ${{ steps.version.outputs.new_version }}
            - Published to npm: https://www.npmjs.com/package/@akitectio/aki-ui

            ## Installation
            ```bash
            npm install @akitectio/aki-ui@${{ steps.version.outputs.new_version }}
            ```
          draft: false
          prerelease: false
